version: '3.9'

services:

  tgbot:
    container_name: web
    restart: always
    build: .
    ports:
      - ${APP_HOST}:${APP_PORT}:8000
    env_file:
      - .env
    command:
      sh scripts/run_web.sh
    volumes:
      - ../static:/app/static
      - ./tgbot_db.sqlite3:/app/tgbot_db.sqlite3
    networks:
      - bot-network

networks:
  bot-network:
    external: false
