# Generated by Django 4.1.2 on 2022-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("message_text", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name_plural": "About Me",
            },
        ),
        migrations.CreateModel(
            name="BotUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("about_me_msg_id", models.IntegerField(default=0)),
                ("reason_to_take_me_msg_id", models.IntegerField(default=0)),
                (
                    "current_location",
                    models.CharField(default="main_menu", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReasonToTakeMe",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("message_text", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name_plural": "Reasons To Take Me",
            },
        ),
    ]
